services:
  postgres:
    image: postgres:12.16-bullseye
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./config/db.sh:/docker-entrypoint-initdb.d/db.sh


